name: SimpleHomes
version: BETA 0.1
author: monsterman04
main: com.monsterman04.SimpleHomes.Main
api-version: 1.17
commands:
  sethome:
    description: Creates new home on your location!
    usage: /<command> <name>
  home:
    description: Teleports you home!
    usage: /<command> <home>
  homes:
    description: Sends you list of your homes!
    usage: /<command>
  deletehome:
    description: Deletes given home
    usage: /<command> <home>
  selecthome:
    description: Home teleport menu
    usage: /<command>